version: "3.8"

services:
  db:
    image: postgres:17-alpine
    container_name: todo_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./backend
    container_name: todo_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: taskdb
      PORT: 5000
    depends_on:
      - db
  web:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://api:5000
    depends_on:
      - api
